/* Pokemon */
export const ADD_POKEMON             = 'ADD_POKEMON'
export const TOGGLE_SELECTED_POKEMON = 'TOGGLE_SELECTED_POKEMON'

/* User */
export const USER_FAILED_LOGIN    = 'USER_FAILED_LOGIN'
export const USER_LOGGED_IN       = 'USER_LOGGED_IN'
export const USER_LOGGING_IN      = 'USER_LOGGING_IN'
export const USER_REGISTERING     = 'USER_REGISTERING'
export const USER_REGISTERED      = 'USER_REGISTERED'
export const USER_FAILED_REGISTER = 'USER_FAILED_REGISTER' 

/* Trainer */
export const FETCHING_TRAINER_INFO        = 'FETCHING_TRAINER_INFO'
export const FETCHED_TRAINER_INFO         = 'FETCHED_TRAINER_INFO'
export const FAILED_TO_FETCH_TRAINER_INFO = 'FAILED_TO_FETCH_TRAINER_INFO'
